### ISSUE TITLE
Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by foxhound87** [sindresorhus/eslint-config-xo-react#5]
When in my `package.json` I use 

```
"xo": {
    "extends": "xo-react"
  }
```

and I run `xo`, it show me: `Cannot find module 'eslint-plugin-react'`

```
❯ xo
Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:125:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:116:21)
    at processText (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:204:5)
    at processFile (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:270:18)
    at executeOnFile (/usr/local/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:617:23)
```

my dependencies are:

```
    "babel-eslint": "^5.0.0",
    "babel-loader": "^6.2.2",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "eslint": "^2.1.0",
    "eslint-config-xo": "^0.10.1",
    "eslint-config-xo-react": "^0.4.0",
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-react": "^3.16.1",
    "webpack": "^1.12.13",
    "xo": "^0.12.1"
```

**Comment by sindresorhus** [comment]
This is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`.

**Comment by mythfish** [comment]
+1, still show "Cannot find module 'eslint-plugin-react''' after running  `$npm cache clean` and `$npm install`.

**Comment by mythfish** [comment]
It seems the reason is the eslint is installed globally. https://github.com/eslint/eslint/issues/3782

**Comment by mythfish** [comment]
Sorry, the real reason is I install xo globally. :(
